name: Informasi Salah/Outdated
description: Laporkan informasi yang salah atau kadaluwarsa.
title: "[Informasi Salah]: "
labels: ["misleading"]
body:
  - type: markdown
    attributes:
      value: |
         ## Informasi Salah/Outdated
        Terima kasih telah melaporkan masalah informasi yang salah atau kadaluwarsa. Silakan lengkapi detail di bawah ini untuk membantu kami memperbaiki dan memperbarui informasi yang tidak akurat atau tidak relevan lagi.
  - type: input
    id: salah
    attributes:
      label: Informasi apa yang salah atau kadaluwarsa?
      description: Harap jelaskan dengan detail tentang informasi yang salah atau kadaluwarsa.
    validations:
      required: true
  - type: input
    id: benar
    attributes:
      label: Informasi yang benar
      description: Silahkan jelaskan di sini.
    validations:
      required: true
  - type: input
    id: refrensi
    attributes:
      label: Referensi
      description: Jika ada, silakan berikan referensi atau sumber yang mendukung klaim Anda tentang informasi yang salah atau kadaluwarsa.
    validations:
      required: false
  - type: textarea
    id: tambahan
    attributes:
      label: Informasi tambahan
      description: Apakah Anda memiliki informasi tambahan atau komentar yang ingin disertakan? Silakan tulis di sini.
    validations:
      required: false
